- name: Ensures /etc/tnm dir exists
  file: path=/etc/tnm state=directory
  tags: [dnam]

- name: Copy DNA-M files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ dnam_files }}"
  tags: [dnam]

- name: Configure dna-m webstart page
  replace: "dest=/etc/tnm/server.conf
          regexp='# webstart.host:'
          replace='webstart.host: {{ host }}'
          backup=yes"
  tags: [dnam]

- name: Configure dna-m webstart page
  replace: "dest=/etc/tnm/server.conf
          regexp='# main.server.address:'
          replace='main.server.address: {{ host }}'
          backup=yes"
  tags: [dnam]

- name: Install DNA-M
  yum:
    name: "tnm*"
    enablerepo: tnm-dev
    validate_certs: no
    state: present
    update_cache: yes
  tags: [dnam]

- name: Remove repository from a specific repo file
  yum_repository:
    name: transmode
    state: absent
  tags: [dnam]

- name: Import file.sql similar to mysql -u <username> -p <password> < initDb.sql
  mysql_db:
    state: import
    name: all
    target: /opt/transmode/tnm/mainserver/scripts/initDb.sql
  tags: [dnam]

- name: Start tnmserver service
  systemd: state=started name=tnmserver
